<a href="https://colab.research.google.com/github/elanozturk/python/blob/main/Python_8_Hafta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

matris = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [ ]:
matris.ndim

2

In [ ]:
matris.size

9

In [ ]:
matris.shape

(3, 3)

In [ ]:
matris = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [ ]:
matris+2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
matris*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [ ]:
matris!=3

array([[ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
matris>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:
matris-1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
matris/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [ ]:
matris%2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [ ]:
matris**3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]])

In [ ]:
np.ones((4,4)) #4X4 değerleri 1 olan matris oluşturur

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((4,4),dtype="int") #4X4 değerleri integer 1 olan matris oluşturur

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.zeros((4,4,4)) #4X4X4 değerleri 0 olan matris oluşturur

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.full((4,4),26) #4X4 değerleri 26 olan matris oluşturur

array([[26, 26, 26, 26],
       [26, 26, 26, 26],
       [26, 26, 26, 26],
       [26, 26, 26, 26]])

In [ ]:
np.eye(6) #köşeleri 1 olan matris yapma

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(5, k=-2) #Köşegeni kaydırır

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
np.diag([3,5,7,9]) #Köşegendeki sayıları belileyebildiğimiz metot

array([[3, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 9]])

In [ ]:
d = np.diag([3,5,7,9])
d

array([[3, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 9]])

In [ ]:
np.fliplr(d)  #Flip Left-Right yani soldakileri sağa, sağdakileri sola aynalama

array([[0, 0, 0, 3],
       [0, 0, 5, 0],
       [0, 7, 0, 0],
       [9, 0, 0, 0]])

In [ ]:
np.flipud(d)  #Up-down yukarı-aşağı

array([[0, 0, 0, 9],
       [0, 0, 7, 0],
       [0, 5, 0, 0],
       [3, 0, 0, 0]])

In [ ]:
np.flip(d)  #orta noktaya göre

array([[9, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 3]])

In [ ]:
np.rot90(d) #90 derece döndürür

array([[0, 0, 0, 9],
       [0, 0, 7, 0],
       [0, 5, 0, 0],
       [3, 0, 0, 0]])

In [ ]:
np.linspace(20,60,6) #20'den 60'a 6 parçalı bir dizi oluşturur

array([20., 28., 36., 44., 52., 60.])

In [ ]:
np.arange(0,16)  #0'dan 16'ya kadar bir dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np.arange(0,16).reshape(4,4) #yeniden şekillendirme

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#SORU 5X5 matris yapın, köşegeni 1 olsun aynı zamanda 1

a = np.eye(5,k=0)
b = np.eye(5,k=1)
c = np.eye(5,k=2)
d = np.eye(5,k=3)
e = np.eye(5,k=4)
a+b+c+d+e

array([[1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a = np.eye(5)
for i in range(1,5):
  a=a+np.eye(5,k=i)
a

array([[1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

In [ ]:
def yarimat(n):
  a = np.eye(n)
  for i in range(1,n):
    a=a+np.eye(n,k=i)
  return a

In [ ]:
yarimat(7)

array([[1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.randint(0,7,(8,5)) # 0'dan 7'e kadar rastgele sayılardan oluşan 8X5 matris oluşturur

array([[6, 4, 5, 2, 5],
       [2, 4, 4, 0, 5],
       [2, 4, 4, 3, 4],
       [2, 2, 4, 0, 0],
       [2, 0, 3, 4, 6],
       [1, 4, 1, 5, 5],
       [0, 4, 2, 6, 4],
       [1, 2, 2, 6, 4]])

In [ ]:
a = np.random.randint(0,2,(4,4))
b = np.random.randint(0,2,(4,4))
b
#İkisinin birbirine eşit olma durumu kaçıncı seferde olur

array([[1, 1, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [ ]:
np.all(a==b) #Hepsi mi eşit sorgular. Hepsi eşitse true verir.

False

In [ ]:
np.any(a==b) #Herhangi biri true ise true verir.

In [ ]:
a = np.random.randint(0,2,(4,4))
b = np.random.randint(0,2,(4,4))

sayac=0
while np.all(a==b)==False:
  sayac=sayac+1
  a = np.random.randint(0,2,(4,4))
  b = np.random.randint(0,2,(4,4))
print("Tebrikler ",sayac," denemede tutturdunuz")


Tebrikler  97335  denemede tutturdunuz


In [ ]:
# 3 tane çay 5 tane kahve = 180 TL
# 4 tane çay 2 tane kahve = 100 TL
# ise çayın ve kahvenin fiyatı nedir? (İki bilinmeyenli denklem)

# 3x+5y=180  12x+20y=720
# 4x+2y=100  12x+6y =300
                #14y=420 y=30 x = 10

katsayilar = np.array([[3,5],[4,2]])
sonuclar = np.array([180,100])
np.linalg.solve(katsayilar,sonuclar)

array([10., 30.])

In [ ]:
np.pi #pi sayısı

3.141592653589793

In [ ]:
np.e #Euler

2.718281828459045

In [ ]:
np.sin(30)  #Radyan cinsinden

-0.9880316240928618

In [ ]:
np.sin(np.deg2rad(30))

0.49999999999999994

In [ ]:
m = np.arange(0,16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
m.max() #matristeki max değeri verir. böyle de yapılabilir np.max(m)

15

In [ ]:
m.min() #min değer

0

In [ ]:
m.mean() #değerlerin ortalaması

7.5

In [ ]:
m.std()  #standart sapma

4.6097722286464435

In [ ]:
np.where(m%2==0,"çift","tek")

array([['çift', 'tek', 'çift', 'tek'],
       ['çift', 'tek', 'çift', 'tek'],
       ['çift', 'tek', 'çift', 'tek'],
       ['çift', 'tek', 'çift', 'tek']], dtype='<U4')

In [ ]:
sayilar = np.array(["1.2","2.3","3.5"])
sayilar.dtype
sayilar.astype("float64")

array([1.2, 2.3, 3.5])

In [ ]:
tarihler = np.array(["2023-12-11","2025-04-13","2021-10-15"])
tarihler.astype("datetime64").max()

numpy.datetime64('2025-04-13')

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
lego = pd.read_csv("sets.csv")

In [ ]:
lego.info() #dataframe genel bilgileri

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Set_ID            14936 non-null  object 
 1   Name              14936 non-null  object 
 2   Year              14936 non-null  int64  
 3   Theme             14936 non-null  object 
 4   Theme_Group       14915 non-null  object 
 5   Subtheme          11495 non-null  object 
 6   Category          14936 non-null  object 
 7   Packaging         14936 non-null  object 
 8   Num_Instructions  14936 non-null  int64  
 9   Availability      14936 non-null  object 
 10  Pieces            13133 non-null  float64
 11  Minifigures       7686 non-null   float64
 12  Owned             14771 non-null  float64
 13  Rating            14936 non-null  float64
 14  USD_MSRP          5837 non-null   float64
 15  Total_Quantity    12276 non-null  float64
 16  Current_Price     5442 non-null   float6

In [ ]:
lego.head(4)  #İlk 4 satırı verir

Set_ID            Name  Year      Theme Theme_Group Subtheme Category  \
0   75-1   PreSchool Set  1975  PreSchool  Pre-school      NaN   Normal   
1   77-1   PreSchool Set  1975  PreSchool  Pre-school      NaN   Normal   
2  077-1  Pre-School Set  1975      Duplo  Pre-school      NaN   Normal   
3   78-1   PreSchool Set  1975  PreSchool  Pre-school      NaN   Normal   

         Packaging  Num_Instructions     Availability  Pieces  Minifigures  \
0  {Not specified}                 0  {Not specified}    16.0          NaN   
1  {Not specified}                 0  {Not specified}    20.0          NaN   
2  {Not specified}                 0  {Not specified}    21.0          NaN   
3  {Not specified}                 0  {Not specified}    32.0          NaN   

   Owned  Rating  USD_MSRP  Total_Quantity  Current_Price  
0   10.0     0.0       NaN             NaN            NaN  
1   11.0     0.0       NaN             NaN            NaN  
2   10.0     0.0       NaN             0.0            NaN  
3    8.0     0.0       NaN             NaN            NaN

In [ ]:
lego.tail(6)

Set_ID                     Name  Year Theme    Theme_Group  \
14930  854241-1  Scarlet Witch Key Chain  2023  Gear  Miscellaneous   
14931  854242-1        Creeper Key Chain  2023  Gear  Miscellaneous   
14932  854243-1          Steve Key Chain  2023  Gear  Miscellaneous   
14933  854244-1         Piglin Key Chain  2023  Gear  Miscellaneous   
14934  854245-1   Fennec Shand Key Chain  2023  Gear  Miscellaneous   
14935  854246-1  Scout Trooper Key Chain  2023  Gear  Miscellaneous   

                   Subtheme Category Packaging  Num_Instructions  \
14930     Key Chains/Marvel     Gear       Tag                 0   
14931  Key Chains/Minecraft     Gear       Tag                 0   
14932  Key Chains/Minecraft     Gear       Tag                 0   
14933  Key Chains/Minecraft     Gear       Tag                 0   
14934  Key Chains/Star Wars     Gear       Tag                 0   
14935  Key Chains/Star Wars     Gear       Tag                 0   

         Availability  Pieces  Minifigures  Owned  Rating  USD_MSRP  \
14930  LEGO exclusive     NaN          NaN   88.0     0.0      5.99   
14931  LEGO exclusive     NaN          NaN    2.0     0.0      5.99   
14932  LEGO exclusive     NaN          NaN    2.0     0.0      5.99   
14933  LEGO exclusive     NaN          NaN    2.0     0.0      5.99   
14934  LEGO exclusive     NaN          NaN   88.0     0.0      5.99   
14935  LEGO exclusive     NaN          NaN  107.0     0.0      5.99   

       Total_Quantity  Current_Price  
14930             NaN            NaN  
14931             NaN            NaN  
14932             NaN            NaN  
14933             NaN            NaN  
14934             NaN            NaN  
14935             NaN            NaN

In [ ]:
lego.sample(8) # rastgele örnek getirir

Set_ID                                           Name  Year  \
12717   70665-1                               The Samurai Mech  2019   
8633     8200-1             Radiator Springs Lightning McQueen  2011   
12030   30382-1                      Baby Velociraptor Playpen  2018   
9389   850417-1                               Monkey Key Chain  2012   
7776   852554-1                           Star Wars Magnet Set  2009   
14371   75322-1                                     Hoth AT-ST  2022   
12863   75262-1  Imperial Dropship  – 20th Anniversary Edition  2019   
14489   21248-1                                            {?}  2023   

                Theme       Theme_Group           Subtheme Category  \
12717         Ninjago  Action/Adventure            General   Normal   
8633             Cars          Licensed      Original Film   Normal   
12030  Jurassic World          Licensed     Fallen Kingdom   Normal   
9389             Gear     Miscellaneous  Key Chains/Animal     Gear   
7776             Gear     Miscellaneous  Magnets/Star Wars     Gear   
14371       Star Wars          Licensed          Episode V   Normal   
12863       Star Wars          Licensed   Original Content   Normal   
14489       Minecraft          Licensed                NaN   Normal   

             Packaging  Num_Instructions     Availability  Pieces  \
12717              Box                 2           Retail   154.0   
8633               Box                 2  {Not specified}    35.0   
12030          Polybag                 2      Promotional    48.0   
9389   {Not specified}                 0  {Not specified}     NaN   
7776   {Not specified}                 0  {Not specified}     NaN   
14371              Box                 2           Retail   586.0   
12863              Box                10           Retail   125.0   
14489  {Not specified}                 0  {Not specified}     NaN   

       Minifigures    Owned  Rating  USD_MSRP  Total_Quantity  Current_Price  
12717          3.0   4134.0     3.9     14.99             7.0          24.99  
8633           1.0   4897.0     3.4      6.99             3.0          35.00  
12030          NaN   6964.0     3.7      3.99            52.0           6.00  
9389           NaN    122.0     0.0      4.99             NaN            NaN  
7776           3.0   1261.0     4.0     14.99             NaN            NaN  
14371          4.0   9804.0     4.2     49.99            11.0          35.30  
12863          5.0  12640.0     4.0     19.99            32.0          37.89  
14489          NaN      NaN     0.0       NaN             NaN            NaN

In [ ]:
#https://data.ibb.gov.tr/dataset/istanbul-barajlarina-dusen-gunluk-toplam-yagis-miktari
pd.read_excel("baraj.xlsx")

Tarih  Ömerli  Darlik  Elmali  Terkos  B.çekmece  Sazlidere  Alibey  \
0    2011-01-01    0.00    0.00    0.00    0.00       0.00       0.00    0.00   
1    2011-01-02    0.00    0.00    0.00    0.00       0.00       0.00    0.00   
2    2011-01-03    0.00    0.00    0.00    0.42       1.37       0.87    0.20   
3    2011-01-04    8.08   10.01   11.64   18.82       9.64      14.72   13.50   
4    2011-01-05    2.78    8.48    7.09    3.42       0.83       4.31    4.30   
...         ...     ...     ...     ...     ...        ...        ...     ...   
4709 2023-11-23   12.68   15.01   11.56   21.40      10.80      12.01    9.12   
4710 2023-11-24    1.08    1.00    0.48    0.20       0.20       0.20    0.20   
4711 2023-11-25    0.00    0.00    0.00    0.00       0.00       0.00    0.00   
4712 2023-11-26   10.48    8.00    8.40    7.60       9.60       8.05    6.80   
4713 2023-11-27    0.00    1.20    0.48    0.20       0.20       0.00    0.00   

      Kazandere  Pabuçdere  ıstırancalar  Unnamed: 11  \
0          0.00       0.00          0.00          NaN   
1          0.00       0.00          0.00          NaN   
2          2.26       1.89          1.39          NaN   
3          8.20      10.37         16.47          NaN   
4          1.44       1.60          3.99          NaN   
...         ...        ...           ...          ...   
4709      29.02      28.90         39.00          NaN   
4710       3.20       3.70          3.93          NaN   
4711       0.40       0.60          1.17          NaN   
4712      32.60      31.72         25.36          NaN   
4713       0.00       0.00          0.07          NaN   

      İstanbul günlük tüketim(m³/gün)  
0                             2096199  
1                             2214668  
2                             2092441  
3                             2096199  
4                             2214668  
...                               ...  
4709                          3000640  
4710                          2981242  
4711                          3019121  
4712                          3083616  
4713                          2998407  

[4714 rows x 13 columns]

In [ ]:
pd.read_json("https://raw.githubusercontent.com/mmcloughlin/starbucks/master/locations.json")

city                              name country   longitude  \
0          Hong Kong                   Plaza Hollywood      CN  114.201691   
1          Hong Kong                   Exchange Square      CN  114.158188   
2            Kowloon                     Telford Plaza      CN  114.213440   
3          Hong Kong                 Hong Kong Station      CN  114.158463   
4          Hong Kong            Pacific Place, Central      CN  114.164619   
...              ...                               ...     ...         ...   
25129   Independence             E. 39th and Arrowhead      US  -94.360023   
25130      Middleton                   Allen Boulevard      US  -89.486618   
25131     Chiang Mai            Chiangmai Ram Hospital      TH   98.977798   
25132         Nantes                          Beaulieu      FR    1.534722   
25133  Overland Park  119th & Glenwood - The Fountains      US  -94.661179   

        latitude  store_id  
0      22.340700         1  
1      22.283939         6  
2      22.322870         8  
3      22.284451        13  
4      22.277657        17  
...          ...       ...  
25129  39.048466   1015654  
25130  43.103439   1016244  
25131  18.793341   1016392  
25132  47.205250   1016496  
25133  38.912449   1016413  

[25134 rows x 6 columns]

In [ ]:
pd.read_csv("ogrenci.txt")

Adı       Soyadı  Dogum
0  Gökhan        Kayan   1993
1   Damla  Senbabaoglu   2004
2  Furkan        Kazan   2003

In [ ]:
wiki = pd.read_html("https://tr.wikipedia.org/wiki/%C3%9Clkelere_g%C3%B6re_ya%C5%9Fam_kalitesi_s%C4%B1ralamas%C4%B1")

In [ ]:
wiki1 = wiki[0] #htmlde birkaç tablo varsa istediğimiz sıradaki tabloyu alma

In [ ]:
wiki1.to_csv("yasamendeksi.txt") #CSV formatında kaydetme(çıkartma)

In [ ]:
pd.read_excel("yasamendeksi.xlsx")

In [ ]:
star = pd.read_json("https://raw.githubusercontent.com/mmcloughlin/starbucks/master/locations.json")

In [ ]:
star.tail(3)

city                              name country  longitude  \
25131     Chiang Mai            Chiangmai Ram Hospital      TH  98.977798   
25132         Nantes                          Beaulieu      FR   1.534722   
25133  Overland Park  119th & Glenwood - The Fountains      US -94.661179   

        latitude  store_id  
25131  18.793341   1016392  
25132  47.205250   1016496  
25133  38.912449   1016413

In [ ]:
#skaler(0), vektörel(1), matris(2), tensor(3 ve üzeri)
star.ndim

2

In [ ]:
star.shape

(25134, 6)

In [ ]:
star["city"]  #istediğimiz kolonu getirelim

0            Hong Kong
1            Hong Kong
2              Kowloon
3            Hong Kong
4            Hong Kong
             ...      
25129     Independence
25130        Middleton
25131       Chiang Mai
25132           Nantes
25133    Overland Park
Name: city, Length: 25134, dtype: object

In [ ]:
filtre = star["country"]=="TR"
star[filtre]

In [ ]:
star[star["country"]=="TR"]

city                  name country  longitude   latitude  store_id
3796      Ankara             Starbucks      TR  32.860321  39.903343      5911
3797    Istanbul             Starbucks      TR  29.125214  40.992905      5912
3798    Istanbul             Starbucks      TR  28.988503  41.030354      5913
3799    Istanbul             Starbucks      TR  29.123409  40.926819      5914
3800      Ankara             Starbucks      TR  32.832993  39.848011      5915
...          ...                   ...     ...        ...        ...       ...
24911     Ankara          Iran Caddesi      TR  32.862816  39.898464   1015948
24926  Eskisehir              Visnelik      TR  30.505999  39.764587   1015846
24945   Istanbul  Garanti Zincirlikuyu      TR  29.018337  41.074856   1015653
25093   Istanbul     Palladium Reserve      TR  29.100069  40.986504   1015831
25102   Istanbul       ACIBADEM NO 190      TR  29.051798  41.010307   1016315

[319 rows x 6 columns]

In [ ]:
#SORU Diyarbakir ve Eskisehir'deki starbucksları
f1 = star["city"]=="Eskisehir"
f2 = star["city"]=="Diyarbakir"

sube = star[f1|f2]

In [ ]:
sube.to_excel("sube.xlsx")

In [ ]:
star[star["country"]=="TR"]

city                  name country  longitude   latitude  store_id
3796      Ankara             Starbucks      TR  32.860321  39.903343      5911
3797    Istanbul             Starbucks      TR  29.125214  40.992905      5912
3798    Istanbul             Starbucks      TR  28.988503  41.030354      5913
3799    Istanbul             Starbucks      TR  29.123409  40.926819      5914
3800      Ankara             Starbucks      TR  32.832993  39.848011      5915
...          ...                   ...     ...        ...        ...       ...
24911     Ankara          Iran Caddesi      TR  32.862816  39.898464   1015948
24926  Eskisehir              Visnelik      TR  30.505999  39.764587   1015846
24945   Istanbul  Garanti Zincirlikuyu      TR  29.018337  41.074856   1015653
25093   Istanbul     Palladium Reserve      TR  29.100069  40.986504   1015831
25102   Istanbul       ACIBADEM NO 190      TR  29.051798  41.010307   1016315

[319 rows x 6 columns]

In [ ]:
star["me_lon"]=29.02373
star["me_lat"]=40.98911
star

city                              name country   longitude  \
0          Hong Kong                   Plaza Hollywood      CN  114.201691   
1          Hong Kong                   Exchange Square      CN  114.158188   
2            Kowloon                     Telford Plaza      CN  114.213440   
3          Hong Kong                 Hong Kong Station      CN  114.158463   
4          Hong Kong            Pacific Place, Central      CN  114.164619   
...              ...                               ...     ...         ...   
25129   Independence             E. 39th and Arrowhead      US  -94.360023   
25130      Middleton                   Allen Boulevard      US  -89.486618   
25131     Chiang Mai            Chiangmai Ram Hospital      TH   98.977798   
25132         Nantes                          Beaulieu      FR    1.534722   
25133  Overland Park  119th & Glenwood - The Fountains      US  -94.661179   

        latitude  store_id    me_lon    me_lat  
0      22.340700         1  29.02373  40.98911  
1      22.283939         6  29.02373  40.98911  
2      22.322870         8  29.02373  40.98911  
3      22.284451        13  29.02373  40.98911  
4      22.277657        17  29.02373  40.98911  
...          ...       ...       ...       ...  
25129  39.048466   1015654  29.02373  40.98911  
25130  43.103439   1016244  29.02373  40.98911  
25131  18.793341   1016392  29.02373  40.98911  
25132  47.205250   1016496  29.02373  40.98911  
25133  38.912449   1016413  29.02373  40.98911  

[25134 rows x 8 columns]

In [ ]:
# mesafe hesabı = ( (x1-x2)**2 + (y1-y2)**2 )**0.5

In [ ]:
star["mesafe"] = ((star["longitude"]-star["me_lon"])**2 + (star["latitude"]-star["me_lat"])**2)**0.5



In [ ]:
star["mesafe"] = star["mesafe"]*100

In [ ]:
star.sort_values(by="mesafe") #sıralama metodu

NameError: name 'star' is not defined

In [ ]:
star.sort_values(by="mesafe",ascending=False) #sıralama metodu

city                                 name country  \
4567             Koloa               Poipu Shopping Village      US   
9882             Lihue                   Kukui Grove Center      US   
22502            Lihue                  Safeway-Lihue #2894      US   
13086            Lihue                  LIH Rotunda (Kauai)      US   
5643             Kapaa  Kauai Village Shopping Center Kapaa      US   
...                ...                                  ...     ...   
3879          Istanbul                            Starbucks      TR   
22547         Istanbul                        Kosuyolu Park      TR   
3860          Istanbul                            Starbucks      TR   
3878   Istanbul - Asya                            Starbucks      TR   
3818          Istanbul                            Starbucks      TR   

        longitude   latitude  store_id    me_lon    me_lat        mesafe  
4567  -159.458832  21.879017      6981  29.02373  40.98911  18944.886317  
9882  -159.379578  21.970592     13923  29.02373  40.98911  18936.079408  
22502 -159.376984  21.971062   1007453  29.02373  40.98911  18935.816608  
13086 -159.348999  21.978167     18197  29.02373  40.98911  18932.960944  
5643  -159.321503  22.062841      8301  29.02373  40.98911  18929.376725  
...           ...        ...       ...       ...       ...           ...  
3879    29.043661  41.003284      6026  29.02373  40.98911      2.445740  
22547   29.036791  41.006020   1013669  29.02373  40.98911      2.136633  
3860    29.031612  40.999626      5996  29.02373  40.98911      1.314237  
3878    29.023642  40.980648      6025  29.02373  40.98911      0.846242  
3818    29.023399  40.990471      5936  29.02373  40.98911      0.140048  

[25134 rows x 9 columns]

In [ ]:
sampi = pd.read_csv("tcl.csv",delimiter=";")
sampi.head(3)

year        team  played  won  drawn  lost  goals_for  goals_against  \
0  1959  Fenerbahce      16   13      2     1         33              8   
1  1960    Besiktas      38   29      7     2         68             15   
2  1961  Fenerbahce      38   26      9     3         81             29   

   goal_difference  points  
0               25      28  
1               53      65  
2               52      61

In [ ]:
f1 = sampi["points"]>80
sampi[f1]

year         team  played  won  drawn  lost  goals_for  goals_against  \
29  1988  Galatasaray      38   27      9     2         86             35   
30  1989   Fenerbahce      36   29      6     1        103             27   
37  1996   Fenerbahce      34   26      6     2         68             19   
38  1997  Galatasaray      34   25      7     2         90             30   
44  2003     Besiktas      34   26      7     1         63             21   
47  2006  Galatasaray      34   26      5     3         82             34   
52  2011   Fenerbahce      34   26      4     4         84             34   

    goal_difference  points  
29               51      90  
30               76      93  
37               49      84  
38               60      82  
44               42      85  
47               48      83  
52               50      82

In [ ]:
f2 = sampi["lost"]==0  #Namağlup Tek Şampiyon
sampi[f2]

year      team  played  won  drawn  lost  goals_for  goals_against  \
33  1992  Besiktas      30   23      7     0         58             20   

    goal_difference  points  
33               38      76

In [ ]:
sampi["team"].value_counts() #her takımın kaç kez şampiyon olduğu

Galatasaray    21
Fenerbahce     19
Besiktas       13
Trabzonspor     6
Bursaspor       1
Name: team, dtype: int64

In [ ]:
sampi.tail(2)

year         team  played  won  drawn  lost  goals_for  goals_against  \
58  2017     Besiktas      34   23      8     3         73             30   
59  2018  Galatasaray      34   24      3     7         75             33   

    goal_difference  points  
58               43      77  
59               42      75

In [ ]:
f1=sampi["points"]>70
f2=sampi["team"]=="Galatasaray"

sampi[f1&f2]

year         team  played  won  drawn  lost  goals_for  goals_against  \
29  1988  Galatasaray      38   27      9     2         86             35   
38  1997  Galatasaray      34   25      7     2         90             30   
39  1998  Galatasaray      34   23      6     5         86             43   
40  1999  Galatasaray      34   23      9     2         85             30   
41  2000  Galatasaray      34   24      7     3         77             23   
43  2002  Galatasaray      34   24      6     4         75             31   
47  2006  Galatasaray      34   26      5     3         82             34   
49  2008  Galatasaray      34   24      7     3         64             23   
53  2012  Galatasaray      34   23      8     3         69             24   
54  2013  Galatasaray      34   21      8     5         66             35   
56  2015  Galatasaray      34   24      5     5         60             35   
59  2018  Galatasaray      34   24      3     7         75             33   

    goal_difference  points  
29               51      90  
38               60      82  
39               43      75  
40               55      78  
41               54      79  
43               44      78  
47               48      83  
49               41      79  
53               45      77  
54               31      71  
56               25      77  
59               42      75

In [ ]:
sampi["kayip"] =sampi["drawn"] + sampi["lost"]
sampi

year         team  played  won  drawn  lost  goals_for  goals_against  \
0   1959   Fenerbahce      16   13      2     1         33              8   
1   1960     Besiktas      38   29      7     2         68             15   
2   1961   Fenerbahce      38   26      9     3         81             29   
3   1962  Galatasaray      38   23     11     4         52             18   
4   1963  Galatasaray      22   14      7     1         54             14   
5   1964   Fenerbahce      34   21     11     2         55             14   
6   1965   Fenerbahce      30   18     11     1         52             13   
7   1966     Besiktas      30   20      8     2         52             16   
8   1967     Besiktas      32   16     13     3         44             15   
9   1968   Fenerbahce      32   19     11     2         38             12   
10  1969  Galatasaray      30   19      8     3         49             14   
11  1970   Fenerbahce      30   17     10     3         31              6   
12  1971  Galatasaray      30   17      8     5         51             18   
13  1972  Galatasaray      30   17      8     5         34             14   
14  1973  Galatasaray      30   19      9     2         47             12   
15  1974   Fenerbahce      30   15     13     2         39             15   
16  1975   Fenerbahce      30   15     13     2         43             18   
17  1976  Trabzonspor      30   17      9     4         36             14   
18  1977  Trabzonspor      30   18      7     5         41             12   
19  1978   Fenerbahce      30   17      8     5         48             24   
20  1979  Trabzonspor      30   13     16     1         34              7   
21  1980  Trabzonspor      30   12     15     3         25             11   
22  1981  Trabzonspor      30   16      7     7         41             21   
23  1982     Besiktas      32   14     16     2         38             17   
24  1983   Fenerbahce      34   18     13     3         43             20   
25  1984  Trabzonspor      34   18     14     2         43             14   
26  1985   Fenerbahce      34   18     14     2         65             25   
27  1986     Besiktas      36   22     12     2         65             21   
28  1987  Galatasaray      36   23      8     5         55             24   
29  1988  Galatasaray      38   27      9     2         86             35   
30  1989   Fenerbahce      36   29      6     1        103             27   
31  1990     Besiktas      34   23      6     5         77             20   
32  1991     Besiktas      30   20      9     1         63             24   
33  1992     Besiktas      30   23      7     0         58             20   
34  1993  Galatasaray      30   20      6     4         74             21   
35  1994  Galatasaray      30   22      4     4         67             28   
36  1995     Besiktas      34   24      7     3         80             26   
37  1996   Fenerbahce      34   26      6     2         68             19   
38  1997  Galatasaray      34   25      7     2         90             30   
39  1998  Galatasaray      34   23      6     5         86             43   
40  1999  Galatasaray      34   23      9     2         85             30   
41  2000  Galatasaray      34   24      7     3         77             23   
42  2001   Fenerbahce      34   24      4     6         82             39   
43  2002  Galatasaray      34   24      6     4         75             31   
44  2003     Besiktas      34   26      7     1         63             21   
45  2004   Fenerbahce      34   23      7     4         82             41   
46  2005   Fenerbahce      34   26      2     6         77             24   
47  2006  Galatasaray      34   26      5     3         82             34   
48  2007   Fenerbahce      34   20     10     4         65             31   
49  2008  Galatasaray      34   24      7     3         64             23   
50  2009     Besiktas      34   21      8     5         60             30   


In [ ]:
#ÖDEV
#1 - Tüm puanları 3 puan sistemine göre hesaplayınız
#2 - Bu sisteme (3 puanlık) ne zaman geçilmiş