<a href="https://colab.research.google.com/github/elanozturk/python/blob/main/Ders_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

matris = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])


In [6]:
matris.ndim

2

In [7]:
matris.size

9

In [8]:
matris+2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
matris ==3


array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [10]:
matris!=3

array([[ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
matris>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [12]:
matris/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [13]:
matris**3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]])

In [14]:
np.ones((4,4)) # float yapar

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.ones((4,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
np.zeros(((4,4,4)))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
np.full((4,4),26)

array([[26, 26, 26, 26],
       [26, 26, 26, 26],
       [26, 26, 26, 26],
       [26, 26, 26, 26]])

In [20]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [21]:
np.eye(5, k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.diag([3,5,7,9])

array([[3, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 9]])

In [27]:
d = np.diag([3,5,7,9])

In [28]:
np.fliplr(d)

array([[0, 0, 0, 3],
       [0, 0, 5, 0],
       [0, 7, 0, 0],
       [9, 0, 0, 0]])

In [29]:
np.flipud(d)

array([[0, 0, 0, 9],
       [0, 0, 7, 0],
       [0, 5, 0, 0],
       [3, 0, 0, 0]])

In [30]:
np.flip(d)

array([[9, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 3]])

In [31]:
np.rot90(d)

array([[0, 0, 0, 9],
       [0, 0, 7, 0],
       [0, 5, 0, 0],
       [3, 0, 0, 0]])

In [34]:
np.linspace(20,60,3)

array([20., 40., 60.])

In [36]:
np.arange(0,16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [76]:
np.arange(0,16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
a = np.eye(5, k=0)
b = np.eye(5, k=1)
c = np.eye(5, k=2)
d = np.eye(5, k=3)
e = np.eye(5, k=4)

a+b+c+d+e

array([[1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

In [45]:
sonuc = np.zeros((5, 5))
for i in range(5):
    sonuc += np.eye(5, k=i)

print(sonuc)

[[1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]]


In [50]:
a = np.eye(5)
for i in range(1,5):
  a = a+np.eye(5,k=i)
a

array([[1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

In [51]:
def yarimat(n):
  a = np.eye(n)
  for i in range(1,n):
    a = a+np.eye(n,k=i)
  return a

In [52]:
yarimat(7)

array([[1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [56]:
np.random.randint(0,2,(10,10))

array([[1, 0, 1, 0, 1, 1, 1, 1, 0, 1],
       [1, 1, 0, 1, 0, 0, 1, 0, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 0, 1, 1],
       [0, 1, 0, 1, 1, 0, 0, 0, 1, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 1, 1],
       [1, 0, 1, 1, 0, 0, 0, 1, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 1, 1],
       [1, 0, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 1, 0]])

In [61]:
a = np.random.randint(0,2,(4,4))
b = np.random.randint(0,2,(4,4))

b


# ikisinin birbirine eşit olma durumu kaçıncı seferde gerçekleşir.


array([[0, 1, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 1],
       [0, 0, 1, 1]])

In [ ]:
a = np.random.randint(0,2,(4,4))
b = np.random.randint(0,2,(4,4))



In [64]:
np.all(a==b)

True

In [68]:
a = np.random.randint(0, 2, (4, 4))
b = np.random.randint(0, 2, (4, 4))

sayac = 0
while np.all(a==b) == False:
  sayac = sayac + 1
  a = np.random.randint(0, 2, (4, 4))
  b = np.random.randint(0, 2, (4, 4))
print("Tebrikler ", sayac , "denemede iki matris eşitlendi.")



Tebrikler  55339 denemede iki matris eşitlendi.


In [71]:
#3 çay 5 kahve = 180 TL
#4 çay 2 kahve = 100 TL

#3x+5y=180 12x+20y=720
#4x+2y=100 12x+6y=300
#14y=420 y =30 x= 10

katsayilar = np.array([[3,5],[4,2]])
sonuclar = np.array([180,100])

np.linalg.solve(katsayilar,sonuclar)

array([10., 30.])

In [72]:
np.e

2.718281828459045

In [73]:
np.sin(30)

-0.9880316240928618

In [75]:
np.sin(np.deg2rad(30))

0.49999999999999994

In [74]:
np.pi

3.141592653589793

In [83]:
m = np.arange(0,16).reshape(4,4)


In [84]:
m.max()

15

In [85]:
np.max(m)

15

In [86]:
m.min()

0

In [87]:
m.mean()

7.5

In [88]:
m.std()

4.6097722286464435

In [89]:
np.where(m%2==0,"çift","tek")

array([['çift', 'tek', 'çift', 'tek'],
       ['çift', 'tek', 'çift', 'tek'],
       ['çift', 'tek', 'çift', 'tek'],
       ['çift', 'tek', 'çift', 'tek']], dtype='<U4')

In [91]:
sayilar = np.array(["1.2","2.3","3.5"])
sayilar.dtype
sayilar.astype("float")

array([1.2, 2.3, 3.5])

In [94]:
tarihler = np.array(["2023-12-11","2025-04-13","2021-12-31"])
tarihler.astype("datetime64")



array(['2023-12-11', '2025-04-13', '2021-12-31'], dtype='datetime64[D]')

In [95]:
tarihler = np.array(["2023-12-11","2025-04-13","2021-12-31"])
tarihler.astype("datetime64").max()


numpy.datetime64('2025-04-13')

In [96]:
tarihler = np.array(["2023-12-11","2025-04-13","2021-12-31"])
tarihler.astype("datetime64").min()


numpy.datetime64('2021-12-31')