<a href="https://colab.research.google.com/github/elanozturk/python/blob/main/Ders_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import datetime

bugun = datetime.date.today()
ay = bugun.month
yil = bugun.year

c.execute("SELECT * FROM")

2023

In [9]:
donem1 = datetime.date(yil, 4, 1)
donem2 = datetime.date(yil, 7, 1)
donem3 = datetime.date(yil, 10, 1)
donem4 = datetime.date(yil, 12, 31)

if bugun>donem1:
  aktif=donem1
elif bugun<donem2:
  aktif=donem2
elif bugun<donem3:
  aktif=donem3
else:
  aktif=donem4

conn = sqlite3.connect("demirbasveri.sqlite")
c = conn.cursor()

c.execute("SELECT * FROM amortismandonemler WHERE donem_tarihi=?",aktif)
sonuc = c.fetchall()

for i in sonuc:
  tolam_donem = toplam_donem+i[3]




#NUMPY KÜTÜPHANESİ (MATLAB'A RAKİP),


In [ ]:
import numpy as np
import time

#Hızlı bir Sistem
#Vektörel çalışır
#Çok boyutlu işlemler yapmamızı sağlar
baslangic = time.time()

liste = []

for i in range(1000000):
  x = pow(i,100)
  liste.append(x)

liste


In [19]:
import numpy as np
import time

#Hızlı bir Sistem
#Vektörel çalışır
#Çok boyutlu işlemler yapmamızı sağlar
baslangic = time.time()

liste = []

for i in range(1000000):
  x = pow(i,100)
  liste.append(x)

bitis = time.time()
bitis-baslangic


2.252013921737671

In [22]:
import numpy as np
baslangic = time.time()

sonuc = np.arange(1000000)**100

bitis = time.time()
npsure = bitis-baslangic
npsure



0.01910686492919922

In [23]:
skaler = np.array(1903)
skaler.ndim

0

In [24]:
vektor = np.array([1903,1905,1907,1967])
vektor.ndim

1

In [28]:
matris = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
matris.ndim

2

In [26]:
tensor = np.array([[[[[[1]]]]]])
tensor.ndim

6

In [31]:
#NUMPY METOTLARI
matris.shape #matrisin şeklini verir
matris.size #eleman sayısı
matris.dtype #veri tipi


dtype('int16')

In [30]:
matris = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]],dtype="int16")

matris.dtype

dtype('int16')

In [32]:
matris.shape


(3, 3)

In [33]:
matris.size

9

In [34]:
matris+2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int16)

In [35]:
matris*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]], dtype=int16)

In [36]:
matris==3


array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [37]:
matris[0]

array([1, 2, 3], dtype=int16)

In [38]:
matris[1]

array([4, 5, 6], dtype=int16)

In [56]:
matris = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [44]:
matris[0][2]

3

In [45]:
matris[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
matris[0:2][1]

array([4, 5, 6])

In [54]:
matris[0:2,2]

array([3, 6])

In [55]:
matris[0,2]

3

In [57]:
matris = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [58]:
matris[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [63]:
matris[1,3]

8

In [62]:
matris[2,3]

12

In [71]:
matris[1:3,3:]


array([[ 8],
       [12]])

In [74]:
matris[2,0]

9

In [75]:
matris[2,3]

12

In [76]:
matris[2:3,0::3]

array([[ 9, 12]])